use_frameworks!
platform :ios, '9.3'

target 'SZMentionsExample' do
pod 'SZMentionsSwift', :git => 'https://github.com/YoungheeJang/SZMentionsSwift.git', :branch => 'develop'
pod 'Hakawai', :git => 'https://github.com/YoungheeJang/Hakawai.git', :branch => 'develop'
end
